spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parqueadero
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
